[package]
name = "rot"
version = "0.1.1"
authors = ["toshokan <toshokan@shojigate.net>"]
edition = "2018"
description = "Type-safe ascii alphabetic byte rotation ciphers"
repository = "https://github.com/toshokan/rot-rs"
license = "MIT/Apache-2.0"

[dependencies]
typenum = "1"
